### ISSUE TITLE
Building got surrounded with fog

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#100]
![2016-07-05 12-46-29](https://cloud.githubusercontent.com/assets/1813101/16581011/551e6170-42b8-11e6-8e1d-d7c6665d8135.png)

**Comment by Andrettin** [comment]
Under what circumstances did that happen? I could not reproduce it here. Did it happen when loading a saved game?

**Comment by KroArtem** [comment]
Unfortunately I don't know. I just left Wyrmsun working and was doing my stuff, then I remembered it's still opened and saw such a strange thing.

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
