### ISSUE TITLE
Cleric without his ability

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#101]
I've created two clerics, one cleric doesn't have his ability to heal, another one can do it.
![2016-07-05 16-59-47](https://cloud.githubusercontent.com/assets/1813101/16587287/f17acc6c-42da-11e6-8c26-d1e55308b741.png)

**Comment by Andrettin** [comment]
I can't reproduce the bug unfortunately :(

**Comment by KroArtem** [comment]
The next time I got such a problem, I'll attach a savegame.

**Comment by Andrettin** [comment]
Did your cleric perchance use a scroll of forgetfulness? I've found a bug with the "retrain" effect of the scroll that would cause this issue for priests, which I fixed here:
https://github.com/Andrettin/Wyrmgus/commit/4e31ea9442bf67def420525c1c33c8dab663b1e1

**Comment by KroArtem** [comment]
Hmm, no, there were no scrolls there at all.

**Comment by KroArtem** [comment]
It happens when you load saved game. I have Witness with two abilities on the bottom of the map. After loading he doesn't have any abilities.
[autosave.sav.gz](https://github.com/Andrettin/Wyrmsun/files/357906/autosave.sav.gz)

**Comment by Andrettin** [comment]
Thank you! The issue has been corrected:
https://github.com/Andrettin/Wyrmgus/commit/2e2a17ee179bb336a596610504d5dbc96aa108ad
