### ISSUE TITLE
Clerics allows to spend unlimited money on potions

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#102]
Try to create a cleric. While he is creating, click on potions. You can spend whatever amount of money you want, but after cleric is created, you'll get only those amount of potions that is available.

**Comment by Andrettin** [comment]
Thank you! I've fixed this now, so that buying items happens immediately even if training a unit:
https://github.com/Andrettin/Wyrmgus/commit/1705809c073030585e7a178143b7c5a4c157c785
