### ISSUE TITLE
Archers are not profitable custom heroes

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#103]
Leaving description blank, will fill it later.

Currently archers have only two abilities and are easy to be killed. Due to their small hp they don't get healed automatically by potions in time. I haven't checked it properly but it seems like they can have less items equipped.
All in all: better to use axefighter/erala/krieger.

**Comment by Andrettin** [comment]
Archers cannot equip shields, so yes, they can equip one less item. It is planned for them to be able to equip bows as well when those are introduced.

They definitely should get more abilities as time passes, as well as higher-level unit types (I would need to find historical references for elite archers for the latter though). Some ideas for abilities floated around were:
1. Quick Draw (faster attack speed) (passive ability)
2. Bow Mastery (more damage) (passive ability)
3. Tracking (be able to see enemy footprints for a while after they stepped upon a tile) (passive ability)

**Comment by KroArtem** [comment]
I'm not sure about Tracking skill, will it be useful or not. A skill that gives +1 range would be also great.

**Comment by Andrettin** [comment]
An ability that increases range sounds good - though it has to be considered that since bows are planned to increase range, it might make the unit overpowered. Perhaps for archers could get a range increase through better bows, while units who throw axes (i.e. dwarven scouts) would get a range increase through an ability that represents improved throwing.

**Comment by Andrettin** [comment]
An update on this, I've recently added two learnable abilities specific to ranged units, namely Precise Shot and Scouting.

**Comment by KroArtem** [comment]
Nice, I'll have a look when I have enough time.

**Comment by KroArtem** [comment]
Archers still lack profits when you develop to teuton civilization and further. It's possible to get + damage but it is clearly not enough in comparison with kriegers'/ritters' improvements.

**Comment by Zagl0** [comment]
instead +damage, i would suggest adding tactical advantages of having archer hero, like ability to set up traps (resource, mana or limited stock per ability level), or to use web to bind flying units or ability to hide from sight (like tree stumps) by using mana.

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
