### ISSUE TITLE
Not all bats have names

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#104]
![2016-07-11 13-11-54](https://cloud.githubusercontent.com/assets/1813101/16727348/b64f8c04-4771-11e6-8c08-a6698867fdcb.png)

**Comment by Andrettin** [comment]
No bats should have their name appearing, actually, since they aren't selectable (because they don't have a portrait of their own).

**Comment by KroArtem** [comment]
Strange, I feel like they had names ("Bat" or something similar) before.

**Comment by KroArtem** [comment]
I think this ticket can be closed as invalid.
