### ISSUE TITLE
Gryphons in 'A Bargain in Struck' quest are too powerful

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#105]
When this quest starts, you need to do a bunch of things: stone, gold and lumber and it's hard to collect it all rather quickly. Whist I was developing, my gnome (duelist) that stays with wagons was attacked by two gryphons and died. I simply didn't have any possibility to help him.

**Comment by Andrettin** [comment]
Thanks for the report :) Indeed, there shouldn't be any gryphons in the mission. I've fixed it now:
https://github.com/Andrettin/Wyrmsun/commit/a617d952547d3424eb162015b9a162bf2e061b7a

**Comment by KroArtem** [comment]
To be honest, bats in this quest are also too annoying. I'm not able to send help to my duelist and he dies as nobody helps him.

**Comment by KroArtem** [comment]
When 3 bats attack my stonelord and then another 3 come, I have no possibility to win. I think your commit @96116144b made situation that bad.

**Comment by Andrettin** [comment]
I agree that the bats detract from the main point of the mission. I've removed them as well now:
https://github.com/Andrettin/Wyrmsun/commit/7f558760d0a2c2875b39579933e17bc9cb28af20

**Comment by KroArtem** [comment]
Thanks! I wasn't against them all, just there were too much of them.
