### ISSUE TITLE
Is their no way to cross water?

### ISSUE THREAD

**Issue by OlovBARA** [Andrettin/Wyrmsun#107]
I think it's fairly important on maps like Scandinavia.

**Comment by Andrettin** [comment]
You can cross water by building a Dock (requires a Lumber Mill / Carpenter's Shop), and then building a Transport ship. Germanics don't have access to docks though, only the Teutons, Dwarves and Goblins do. Additionally, dwarves can attack through the air with gryphon riders.

**Comment by KroArtem** [comment]
Another way is to use wooden rafts, sometimes they're placed on the shore.

**Comment by KroArtem** [comment]
I think this ticket can be closed. I'm sure information about docks is presented in encyclopedia.
