### ISSUE TITLE
Can't click on the very sides of the map.

### ISSUE THREAD

**Issue by Szunti** [Andrettin/Wyrmsun#11]
If the cursor is on the side it changes to the scrolling one (<< or >>) even on the end of the map, and left clicking for selection and right clicking doesn't work. Maybe the map needs to be narrow to show this behaviour.

**Comment by Andrettin** [comment]
Good point; this has now been fixed in https://github.com/Andrettin/Wyrmgus/commit/2f46ff796add2d3664e5a0aa01b8c4bce18e2353

I made it so the mouse scroll arrow no longer appears if the edge of the map has been reached.
