### ISSUE TITLE
Loading game leads to problems with doors

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#112]
Unzip the same file as in the previous ticket.
[game.sav.zip](https://github.com/Andrettin/Wyrmsun/files/384422/game.sav.zip)

Try to go with heroes through places where doors were destroyed. Heroes cannot go through these doorways.

**Comment by Andrettin** [comment]
Thanks for the report! It is quite curious - the game seems to be saving the door's field flags into their tiles even if the door is "dying", although when playing (before saving and loading) the flag wasn't present in the tile anymore after the door had been destroyed. I'll have to look deeper into it.

**Comment by Andrettin** [comment]
Fixed now:
https://github.com/Andrettin/Wyrmgus/commit/0e45bf478e81f91956cac88e320b99bb44028240
