### ISSUE TITLE
Gliders are not healed

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#113]
Usual swordsmen/impalers are healed whilst gliders are not.
![2016-08-17 18-16-29](https://cloud.githubusercontent.com/assets/1813101/17741977/4fb48fb6-64af-11e6-8ab4-b8860f441ede.png)

**Comment by Andrettin** [comment]
I recently changed the gliders to mechanical units, so they can't be healed (but they can be repaired).

**Comment by KroArtem** [comment]
Got it, thanks.

**Comment by KroArtem** [comment]
By the way, Gliders cannot patrol, it significantly decreases their profit.

**Comment by Andrettin** [comment]
Good point; I've fixed that now:
https://github.com/Andrettin/Wyrmgus/commit/8b43cb5dc4e198454f385f32359fb3961f79f20e
