### ISSUE TITLE
Items lose their names after loading save game

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#117]
I've loaded autosave after the crash (reported it in @Wyrmsun repo) and scrolls and other thins lost their descriptions. As a bonus, I've seen buras standing on stone tiles. (Though these tiles were removed when I came closer).
![2016-08-23 19-26-33](https://cloud.githubusercontent.com/assets/1813101/17900723/5f727afa-6971-11e6-9927-8070ef7ac125.png)
![2016-08-23 19-28-28](https://cloud.githubusercontent.com/assets/1813101/17900724/5f728ca2-6971-11e6-9341-2396b5ffdb7c.png)
![2016-08-23 19-28-42](https://cloud.githubusercontent.com/assets/1813101/17900722/5f721b28-6971-11e6-8712-06c9fc4b9f1e.png)
![2016-08-23 19-30-00](https://cloud.githubusercontent.com/assets/1813101/17900725/5f767088-6971-11e6-9e9a-f7636af6c712.png)

**Comment by Andrettin** [comment]
Thank you! This is fixed now:
https://github.com/Andrettin/Wyrmgus/commit/bc197c823ae5aebe064fcf2fee62daf04725e040
