### ISSUE TITLE
[Feature request] Autosave time period

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#119]
It'd be cool to be able to set up autosave's period.

**Comment by Andrettin** [comment]
It's a good idea :) Any quantity of minutes in particular you would like to see?

**Comment by KroArtem** [comment]
Either a textbox or a predefined combobox with available choices would be good.

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
