### ISSUE TITLE
[Feature Request] Show your opponents dynamically in status/objectives

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#120]
It'd be a good idea to know who is still alive and who needs to be destroyed. Probably you've ever played AoE II, there was a possibility to show your and your opponents' progress in down right part of the screen.

**Comment by Andrettin** [comment]
I agree. Maybe making the opponents' name appear striken-through if they're defeated in the list of players that appears when nothing is selected.

**Comment by KroArtem** [comment]
Btw, I still don't know how to call it (how to make it appear in botpanel).

**Comment by Andrettin** [comment]
Oh, just press "^" and then all units should be deselected and it will appear.

**Comment by KroArtem** [comment]
Thanks!

**Comment by KroArtem** [comment]
As far as I understand, when a tribe is destroyed, it's removed from opponents' list now, right?

**Comment by Andrettin** [comment]
Yes, if a player is completely destroyed they no longer show up. The reason for this was that there wasn't enough space to show all opponents if there were too many of them.

**Comment by KroArtem** [comment]
So this ticket is more or less completed. If you have no plans working on it anymore, feel free to close. :)
