### ISSUE TITLE
Can't queue food pickups

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmsun#123]
For hero units, you can shift-click to pick up one potion or food item after another, but with other units they will stop once they pick up (i.e. consume) the first one.  For example, if you shift-click to tell a wounded unit to pick up a potion, then a carrot, then a cheese, he will only pick up and consume the potion then stop.

**Comment by Andrettin** [comment]
Thank you! I've fixed the issue :)

https://github.com/Andrettin/Wyrmgus/commit/6a2749f680772580f01d6d1453f0ccde70e915fd
