### ISSUE TITLE
Blank ability icon

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmsun#124]
My hero's Precise Shot icon appears normally when he's selected alone.  When he is selected first, then another skutan is selected, the icon turns either green or black.  If a unit (skutan or not) is selected first, and then my hero, the icon is not shown (this is the correct behavior, I believe?).  If my hero and an erala are selected together, the icon is not shown.

So it appears to only be an issue if a hero with an ability is selected, and then another unit that could learn that ability.

![screenshot_2016-09-10_20-36-23](https://cloud.githubusercontent.com/assets/692397/18414449/77376050-7796-11e6-8343-a15c1a9616d3.png)
![screenshot_2016-09-10_20-42-34](https://cloud.githubusercontent.com/assets/692397/18414464/2dcf1146-7797-11e6-81df-d8468ddbf3cd.png)

**Comment by Andrettin** [comment]
Thanks for the detailed explanation :)

I've solved the problem now:
https://github.com/Andrettin/Wyrmgus/commit/769905db25d6b8d5b00b36e6f8c8103c9d8eecea
