### ISSUE TITLE
Desiderius x5

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmsun#128]
On Grand Strategy Mode playing as the Lombard tribe, all of my units thus far have been named Desiderius, Desiderius Desiderius, Desiderius Desiderius Desiderius, Desiderius Desiderius Desiderius Desiderius, or even Desiderius Desiderius Desiderius Desiderius Desiderius.  I get the feeling this isn't what's supposed to happen.

**Comment by Andrettin** [comment]
Aye, I've added several new Lombard names now to fix this issue:
https://github.com/Andrettin/Wyrmsun/commit/3d0e66323d6069066fc686af44a8e4cc7c541fc2
