### ISSUE TITLE
Initial script rerun when loading a saved game made by the autosave feature (Teuton quest "Home of the Boii")

### ISSUE THREAD

**Issue by akien-mga** [Andrettin/Wyrmsun#13]
In the Teuton quest "Home of the Boii", the tribe chief, Marbod, is a playable character and should not be killed. If he's killed, the game ends with a defeat.

However, after being defeated this way, and when reloading the last autosave, getting Marbod killed again would not trigger the defeat event. I'll upload my autosave.sav.gz somewhere so that you can reproduce the issue.

**Comment by akien-mga** [comment]
autosave.sav.gz: http://dl.free.fr/hNW8mXjKU

**Comment by akien-mga** [comment]
Ah the issue is actually different from my initial guess: when you load autosave.sav.gz, you'll see one Marbod in the Boii base (fighting enemies that we actually already killed before the autosave), and there is another Marbod + initial warriors in the player's base, as if the game start scripts were relaunched when loading the save.

**Comment by akien-mga** [comment]
The issue seems to be in the autosave feature, I don't reproduce the bug with self-made saves. But if I load the autosave attached above, and then wait five minutes for a new autosave, I get 3 Marbods when loading the new autosave :)

**Comment by akien-mga** [comment]
The "Restart Mission" option also behaves weirdly after loading my autosave, the map isn't restarted at all, it just seems to reload the autosave.

**Comment by akien-mga** [comment]
BTW, I'm using the latest git.

**Comment by akien-mga** [comment]
Another persistent issue with this quest: the level of Marbod is not reset if you restart the map completely from scratch (i.e. back to the main menu, and start the quest anew). First time I restarted the quest, Marbod was levelled up to level 3 (instead of level 2 normally), so I chose his new skill. Then I restarted the game again, and Marbod was already level 3.

**Comment by akien-mga** [comment]
It looks like Marbod's level is saved in preferences.lua:
```
$ grep Marbod wyr/preferences.lua 
if (wyr.preferences.Heroes.Marbod == nil) then wyr.preferences.Heroes.Marbod = {} end
if (wyr.preferences.Heroes.Marbod.items == nil) then wyr.preferences.Heroes.Marbod.items = {} end
wyr.preferences.Heroes.Marbod.level = 3
wyr.preferences.Heroes.Marbod.name = "Marbod"
if (wyr.preferences.Heroes.Marbod.upgrades == nil) then wyr.preferences.Heroes.Marbod.upgrades = {} end
wyr.preferences.Heroes.Marbod.upgrades[1] = "upgrade-sword-mastery"
wyr.preferences.Heroes.Marbod.upgrades[2] = "upgrade-critical-strike"
```

**Comment by Andrettin** [comment]
Thanks! I fixed it now:
https://github.com/Andrettin/Wyrmgus/commit/098447542fcc47aac4ea8b091da2c5ee0e0eccd5

About the stats, that's intentional. The idea is to allow players to replay missions (perhaps at a higher difficulty level) to try to level the characters further. Besides that mission, Marbod is also playable in random dungeons.

About preferences.lua, what would you suggest instead?

**Comment by akien-mga** [comment]
> About the stats, that's intentional. The idea is to allow players to replay missions (perhaps at a higher difficulty level) to try to level the characters further. Besides that mission, Marbod is also playable in random dungeons.

OK, sounds good :)

> About preferences.lua, what would you suggest instead?

I don't know, maybe split it in a heroes.lua file? I don't have a strong opinion though, if you like it in preferences.lua, it's fine by me :)
