### ISSUE TITLE
Witnesses have graphics problems with their stick

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#131]
![2016-10-05 02-48-28](https://cloud.githubusercontent.com/assets/1813101/19096767/26a2cd8c-8ab0-11e6-8cb9-b16f323c10e9.png)

**Comment by Andrettin** [comment]
Thanks :) I couldn't reproduce the issue here, but it probably occurred because the mace's graphics weren't indexed to a palette; that is fixed now:
https://github.com/Andrettin/Wyrmsun/commit/fde83413271dd871eca76fded9931ccfe9f6b735

**Comment by KroArtem** [comment]
Will check this evening.

**Comment by KroArtem** [comment]
Works correctly now.
