### ISSUE TITLE
Unnecessary comma in faction description

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#132]
![2016-10-05 02-45-59](https://cloud.githubusercontent.com/assets/1813101/19096934/b4bcd1b6-8ab1-11e6-9ac8-52b922840065.png)

It may be because it's indeed in description (I didn't manage to find it, though) or if description is autogenerated, then it's probably because my hero is from another faction and his "profession" should be somehow showed in this effects string.

**Comment by Andrettin** [comment]
Thank you! This happened because Joruvellir has a special unit type for the Yale Pen which does not have different stats from the default one. I've fixed the issue now:
https://github.com/Andrettin/Wyrmgus/commit/d0ae58262b85c1383a754e8d58805fd77a512b01
