### ISSUE TITLE
Issue with symmetric maps and mercenary camps

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#133]
It's indeed symmetric but looks a bit strange
![2016-10-08 01-30-39](https://cloud.githubusercontent.com/assets/1813101/19207159/668b751a-8cff-11e6-9645-f503703a9490.png)

**Comment by KroArtem** [comment]
The problem is that there are 2 more camps just under these ones.

**Comment by Andrettin** [comment]
I personally don't think it is strange; since the map is symmetric, the mercenary camps would be as well. The two mercenary camps below are because the map is symmetric not only in regards to left-right, but also top-down.

**Comment by KroArtem** [comment]
That sounds like a cheating for me. I managed to get control over these camps and then it was much easier to win.

**Comment by KroArtem** [comment]
I remember you changed something related to symmetric maps after I posted this ticket. Was there anything?

**Comment by Andrettin** [comment]
Yes, but only for player spawn points. I've added a similar check for neutral buildings now, which prevents them from being generated too close to one another; the camp's spawn point must be in a distance of 16 tiles from the borders of the symmetric quadrant:
https://github.com/Andrettin/Wyrmsun/commit/c1520a3424bba9ec426f0823591afcd897d113ce

**Comment by KroArtem** [comment]
All in all it will be at least 32 tiles between two identical neutral buildings. Good, probably this one can be closed then.

**Comment by Andrettin** [comment]
Alright :)
