### ISSUE TITLE
Wyrmsun doesn't start due to hero's weird name

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#138]
I have heroes with such names: `autosave.sav.gz'?.lua` and `autosave.sav.gz'\n.`
It was possible to create them before but now Wyrmsun fails to start the game at all (plus don't forget [this problem](https://github.com/Andrettin/Wyrmsun/issues/38#issuecomment-235340447))

The output is:

```
[string ".//wyr/heroes/custom/autosave.sav.gz'..."]:1: unfinished string near '"autosave.sav.gz''
[Thread 0x7fffd7c9e700 (LWP 5307) exited]
[Thread 0x7fffdccbe700 (LWP 5305) exited]
[Thread 0x7fffdb9cf700 (LWP 5308) exited]
[Inferior 1 (process 5301) exited with code 01]

```

_Edit:_
Actually you can delete your heroes but in that case you won't be able to do it from game.

**Comment by Andrettin** [comment]
Hmm... One thing, why is the save game in the custom heroes folder?

**Comment by KroArtem** [comment]
Sorry, these were not the savegames, just usual heroes

**Comment by Andrettin** [comment]
Ah, thanks for the clarification! I haven't done any changes to the hero loading code lately, so I'm not sure why this is happening now. It looks like the ' is finishing the string, but that is usually done only with ".

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
