### ISSUE TITLE
Loaded game has no objective

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#139]
I've loaded my game but it doesn't seem to have any objections. Moreover, my ally's machine starts to attack me when I'm nearby.
Attaching savegame. Rename sav.txt to sav.gz

[noObjective.sav.txt](https://github.com/Andrettin/Wyrmsun/files/551964/noObjective.sav.txt)

**Comment by Andrettin** [comment]
Thanks! I think I know what happened:
1. You had a saved custom game.
2. You played the campaign mode, and after that you loaded your saved game.
3. The saved game started without any objectives. When you saved it again, the lack of objectives was saved.

There was an issue with the "CurrentCampaign" variable not being reset after playing a campaign, so when you started a scenario, it would remove the default objective as done for the campaign mode. I've fixed that now:
https://github.com/Andrettin/Wyrmsun/commit/c620ee1737cc508f1adea9c5acd19159e88fd7db

You mean your ally's catapult began attacking you when you were nearby? I couldn't reproduce that. With which unit of yours did that happen?

**Comment by KroArtem** [comment]
There is a catapult in the center of the map and if I was going nearby this catapult, it was attacking me (and all other units start doing the same). Currently I'm not able to reproduce this.

I think this issue can be closed.

**Comment by Andrettin** [comment]
Hmm, it's strange. Did you happen to attack the catapult? If that issue appears again, let me know.

**Comment by KroArtem** [comment]
no, of course I wasn't attacking catapult. What made me surprised was the fact that they stopped attacking me after some time.
