### ISSUE TITLE
Units can gather food even when they're far away from it

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#140]
No screenshot this time.
Try to surround your injured unit with other units so it won't be able to move. Say him to pick up food that lays nearby. He'll pick it and it, though not moving at all.

**Comment by Andrettin** [comment]
Thanks! I've fixed that now :)

https://github.com/Andrettin/Wyrmgus/commit/401313be7c94f52c1637b73967b2d7009b9b870e
