### ISSUE TITLE
Knowledge (magic) is not saved in campaigns

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#142]
At least knowledge (magic) is not saved when you save and load the game (campaign mode).

**Comment by Andrettin** [comment]
Was that for a persistent hero or a high level unit? Could you post the saved game in question?

**Comment by KroArtem** [comment]
It was Sigibert, attaching savegame but Sigibert doesn't have any knowledge points (due to this bug).
He's situated on the bottom of the map where orange units are located.
[game2.sav.txt](https://github.com/Andrettin/Wyrmsun/files/560364/game2.sav.txt)

**Comment by Andrettin** [comment]
Thank you! I've fixed it :)
https://github.com/Andrettin/Wyrmgus/commit/f3097a381ff98fc2b35615a6bbf9094f22eba39d
