### ISSUE TITLE
If custom hero has no items in inventory he cannot close it

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#144]
In campaign mode, if a custom hero doesn't have any items in an inventory, he can open it but cannot close it.

![2016-12-06 03-07-18](https://cloud.githubusercontent.com/assets/1813101/20904306/5bcde324-bb58-11e6-948e-98224aaf0bde.png)

**Comment by Andrettin** [comment]
Thanks for letting me know of the bug :) I changed the button level of the inventory, but forgot to change the button level of the cancel button accordingly. This is fixed now.
