### ISSUE TITLE
Dwarves still say "We need more gold!"

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#145]
Instead of copper, I suppose.

**Comment by Andrettin** [comment]
True, but I think it is acceptable since gold converts into copper, and copper represents wealth as well. And getting the voice actors to do the lines for all civilizations again would be complicated.

**Comment by KroArtem** [comment]
I think this one indeed can be closed. I do understand it doesn't work changing to copper. (You may also want to change it back to gold, nobody knows ;) )
