### ISSUE TITLE
Lyr description is overlapped with button

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#147]
![2016-12-22 23-16-17](https://cloud.githubusercontent.com/assets/1813101/21439982/376e4dde-c8aa-11e6-91ab-773377de3617.png)

**Comment by Andrettin** [comment]
Fixed :)

https://github.com/Andrettin/Wyrmgus/commit/34ee9b496d48f7c857c96187ea944b1bab725b23
https://github.com/Andrettin/Wyrmsun/commit/9f779a63f0f0e16c40e1a6f792cc48105c8fca30
