### ISSUE TITLE
Mouse stuck

### ISSUE THREAD

**Issue by ReptilianLucifer** [Andrettin/Wyrmsun#152]
Just got the steam version of this game and was pretty excited to play it. It worked fine for about 5 minutes, but suddenly the screen seemed to glitch down to the bottom right of the computer screen and my mouse did the same thing. Now when i try to move my mouse at all, it's stuck at the bottom right. Reverting my video settings to the default didn't fix this, so i'm not sure what to do now.

**Comment by Andrettin** [comment]
Hey, was your issue resolved?
