### ISSUE TITLE
Not clear requirements to create potions

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#155]
I think one shaman was required to build potions but not sure. When I tried to create a potion a warning was shown like "Not all requirements are fulfilled". 

![2017-04-25 19-16-43](https://cloud.githubusercontent.com/assets/1813101/25448622/c085157a-2ac1-11e7-8b0a-265059a932bb.png)

**Comment by Andrettin** [comment]
Thank you :) This is fixed now:
https://github.com/Andrettin/Wyrmsun/commit/323ab05f3b604faf3a09a8973cc0c44ebbb839fc
