### ISSUE TITLE
Cleric icon when recruiting Gudjan

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmsun#157]
When you upgrade a Germanic civ to the next level (the one that requires bronze swords and shields), recruiting a pagan gudjan from the temple will show the Christian cleric icon in the lower left window.
![screenshot_2017-05-09_14-45-38](https://cloud.githubusercontent.com/assets/692397/25870107/e6acc360-34d0-11e7-993f-fbfefeea2bdc.png)

**Comment by Andrettin** [comment]
Thank you for the report :)

I've fixed the issue:
https://github.com/Andrettin/Wyrmgus/commit/94f506934ad678e4c661ce8fd1f6c6fe204be5ec
