### ISSUE TITLE
SDL mixer for more plateform comptability

### ISSUE THREAD

**Issue by BeWorld2018** [Andrettin/Wyrmsun#158]
hi,
I can't play music on my Amiga Platform.
It's possible to have SDL_Mixer for Music (and sounds) support ?
Thanks you

**Comment by Andrettin** [comment]
The music in the game is handled by an external library - OAML:
https://github.com/oamldev/oaml

Otherwise sounds in the game are already handled through SDL, though.

**Comment by BeWorld2018** [comment]
yes i see that, but this library is incompatible with AmigaOS (MorphOS system).

The sounds work well.

II realize a port for this machine, and it's working well :-)
I have only 2 problems, OpenGL :-( and Music.

**Comment by Andrettin** [comment]
SDL_mixer is indeed now used for audio since version 4.1.0 :)
