### ISSUE TITLE
Bug in techtree

### ISSUE THREAD

**Issue by BeWorld2018** [Andrettin/Wyrmsun#159]
No button to return to menu.

**Comment by Kriss7475** [comment]
The button exists in 3.3.0, what is your version?

**Comment by BeWorld2018** [comment]
After check, it's my translate file.. sorry

So i modify a lot of file (.lua) in script to have more translatable strings.
It's possible to put in this repository ?

**Comment by Andrettin** [comment]
Yup, I am just finishing fixing the bug, having seen the issue earlier on :)

**Comment by Andrettin** [comment]
Fixed now! About making more strings translatable, you could create a pull request with that, or just attach the files here.

In any case, note that some strings (i.e. unit names in unit definitions) shouldn't be set as translatable directly. In those cases it is better to make the UI uses of those strings translatable instead.
