### ISSUE TITLE
Cannot load deleted file

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#16]
Wyrmgus 13779ef19584267f4abdf9f1280caf229293fb9f
Wyrmsun  bdd8d0228705f5f8b52b06e21a67bec40688c177
In one of previous commits /graphics/neutral/icons/cheese.png was deleted. Now Wyrmgus cannot load it during custom games' start, and exits. While I was writing this issue, I understood there was no need to debug Wyrmgus :)

In 74d6d57a148415557b9ca10befac41b978545848 it was deleted, but not removed from /scripts/icons/lua:1287 and /scripts/units/lua:3123

**Comment by Andrettin** [comment]
Thanks! This was an oversight; since the icon was unused, I didn't notice I hadn't fixed its icon. The cheese.png in /scripts/units.lua is another image, so only /scripts/icons.lua had to be changed.

Fixed here:
https://github.com/Andrettin/Wyrmsun/commit/a86a4f683634e93eed91bb1b96afb6f6248e9264
