### ISSUE TITLE
News menu lua files

### ISSUE THREAD

**Issue by BeWorld2018** [Andrettin/Wyrmsun#160]
More translatable strings

I made a big files for french users

There aren't your fix 159.

[menus.zip]

(https://github.com/Andrettin/Wyrmsun/files/1768455/menus.zip)

**Comment by Andrettin** [comment]
Thank you! I've implemented your patch now, while keeping the tech tree fix (and other changes which didn't seem to be in your code yet). The tip strings I didn't make translatable since that can be done in a simpler manner through the engine code.
