### ISSUE TITLE
audio popping

### ISSUE THREAD

**Issue by rynnon** [Andrettin/Wyrmsun#162]
Audio is constantly popping, like it's dropping out every 0.5 seconds. 

Installed through steam
OS: Linux Mint 18
WM: i3
GPU: NVIDIA GTX 970 (proprietary driver)

**Comment by Andrettin** [comment]
The audio system has been reworked to use SDL_mixer 2, so this issue probably no longer applies. Please feel free to reopen it if you still experience this problem!
