### ISSUE TITLE
Game does not remember ended scenarious

### ISSUE THREAD

**Issue by bergentroll** [Andrettin/Wyrmsun#163]
I built the Wyrmsun 3.3.0 on Arch Linux. If I win some scenario, a "(!)" sign disappears from its name and some new scenario arrives in list. But when I exit game and then start it again the scenarios list seems like I did not finish any. Meanwhile savegames work and I have the ".stratagus" dir including "wyr" dir in my home directory.
Also firstly I tried to build the Wyrmsun 3.1.0 from [AUR](https://aur.archlinux.org/packages/wyrmsun/) and had the same issue.

**Comment by Andrettin** [comment]
Thanks for reporting the issue! I've made a commit now that should fix the issue:
https://github.com/Andrettin/Wyrmgus/commit/df5af1234bae91af70c1615a0555c92e81571039

**Comment by bergentroll** [comment]
It seems it works now. Thank you! You fixed the issue very fast. =)

**Comment by Andrettin** [comment]
Great to hear everything is working fine now :)
