### ISSUE TITLE
A bug in quest "A bargain is struck"

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#17]
Wyrmsun c544698265387ebec32d816c06aceea6dd7d3d39
Wyrmgus also the latest.

The aims were "bring caravans to the Mead Hall"
Durin must survive

I've done these aims and was supposed to finish the quest, but a message appeared: We have all of the silver, now all we need is the stone.
I've collected 20,000 of stone and didn't manage to finish the quest.

![2015-10-23 19-59-29](https://cloud.githubusercontent.com/assets/1813101/10710565/b0654ce2-7a68-11e5-813b-16e9de5ee4a9.png)

**Comment by Andrettin** [comment]
Hey, you need to have the gnomish envoy (the gnomish recruit you have control over) next to your mead hall as well (as per the latter part of the first objective). The "stone" mentioned is the ruby the envoy is carrying.

**Comment by KroArtem** [comment]
Now I'm not able to load the savegame as it says:
Color Color not defined
And exits even in the debugger.
Attaching savegame.

https://www.dropbox.com/s/33bthpd63uyf5pe/wut_2.sav.gz?dl=0

**Comment by Andrettin** [comment]
Thank you! With your savegame I was able to debug and fix that save game bug in https://github.com/Andrettin/Wyrmgus/commit/3de8362f24f661c602a36551c31d87a09a7903c4
