### ISSUE TITLE
Part of Wyrmsun screen is black

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#18]
Wyrmsun c544698265387ebec32d816c06aceea6dd7d3d39
I've had this issue only once and didn't manage to reproduce it yet. The right part of the screen was black, see screenshot:

![2015-10-23 16-55-07](https://cloud.githubusercontent.com/assets/1813101/10710586/47a7427c-7a69-11e5-8e74-4001e1b5677a.png)

Note: I wasn't changing resolution or something else during this game session.

**Comment by Andrettin** [comment]
Thanks for reporting this! Interesting how the minimap's "selected" area ends not at the end of your screen, but where the black part of the screen starts. Without being able to reproduce this I'm afraid I won't be able to do much to solve it, however =/

**Comment by Andrettin** [comment]
Fixed https://github.com/Andrettin/Wyrmsun/commit/3824d2f4fd3d2ce9045df7c05f6da4a46ed2607f
