### ISSUE TITLE
windows version not working after I installed the game on linux

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Andrettin/Wyrmsun#185]
I installed both through steam, one windows 10 and the other on linux mint 20.1

I can play it without issue on mint, but now my windows 10 install doesn't load saved games. I haven't tried start a new game, so probably should try that first, but just wanted to check whether or not cross-platform installs through steam conflict with each other?

Steam does it with my other games for some reason.

**Comment by Andrettin** [comment]
What do you mean by not loading saved games, does it crash?

Steam just deploys the game's files and starts its executable, so as long as it does those things correctly it shouldn't have an influence.

**Comment by DinkyDyeAussie** [comment]
The game starts on both no worries, but crashes on windows 10 when I try to load a saved game. No error message, but I will check the folder for a crash report when I get home.

I tried to verify the files on my windows version but it took too long so I cancelled it. But will try again to start a new game after work.

**Comment by Andrettin** [comment]
It sounds like a bug in Wyrmsun. What does your stderr.txt file on the game's folder say?

**Comment by DinkyDyeAussie** [comment]
`[2021.01.30 05:03:43] Character "Marbod" has persistent data, but doesn't exist.
[2021.01.30 05:04:05] Lua error: [string "D:\Steam\steamapps\common\Wyrmsun//wyr/save..."]:28: attempt to call global 'SetCurrentDayOfTheWeek' (a nil value)
stack traceback:
	[string "D:\Steam\steamapps\common\Wyrmsun//wyr/save..."]:28: in main chunk
	[C]: in function 'StartSavedGame'
	[string "scripts/menus/load.lua"]:15: in function 'LoadGame'
	[string "scripts/guichan.lua"]:1314: in function 'RunProgramStartMenu'
	[string "scripts/guichan.lua"]:1401: in main chunk
[2021.01.30 05:04:30] Character "Marbod" has persistent data, but doesn't exist.
Cannot open file D:\Steam\steamapps\common\Wyrmsun//wyr/quests.lua for writing.
[2021.01.30 05:04:36] Lua error: [string "D:\Steam\steamapps\common\Wyrmsun//wyr/save..."]:28: attempt to call global 'SetCurrentDayOfTheWeek' (a nil value)
stack traceback:
	[string "D:\Steam\steamapps\common\Wyrmsun//wyr/save..."]:28: in main chunk
	[C]: in function 'StartSavedGame'
	[string "scripts/menus/load.lua"]:15: in function 'LoadGame'
	[string "scripts/guichan.lua"]:1314: in function 'RunProgramStartMenu'
	[string "scripts/guichan.lua"]:1401: in main chunk
[2021.01.30 05:06:19] Character "Marbod" has persistent data, but doesn't exist.
C:\Wyrmgus\src\unit\unit_type.cpp:477: GetResourceIdByNameResource not found: ore
[2021.01.30 05:06:24] Lua error: Resource not found: ore
stack traceback:
	[C]: in function 'DefineUnitStats'
	[string "D:\Steam\steamapps\common\Wyrmsun//wyr/save..."]:32: in main chunk
	[C]: in function 'StartSavedGame'
	[string "scripts/menus/load.lua"]:15: in function 'LoadGame'
	[string "scripts/guichan.lua"]:1314: in function 'RunProgramStartMenu'
	[string "scripts/guichan.lua"]:1401: in main chunk
`

**Comment by DinkyDyeAussie** [comment]
Sorry, that's a bit messy.

**Comment by Andrettin** [comment]
Was it an old save?

**Comment by DinkyDyeAussie** [comment]
Yeah. I literally tried a new game instead and it's working fine. There must've been a few changes in the code.

**Comment by Andrettin** [comment]
Looking at the error output, that seems to be it, yes. The old save is not compatible with the current version.

**Comment by DinkyDyeAussie** [comment]
Thanks mate. If it was a waste of time I apologize. Just took me by surprise.

**Comment by Andrettin** [comment]
It's no problem at all :)

**Comment by Andrettin** [comment]
I'm closing this, but please feel free to reopen if you wish to discuss anything further!
