### ISSUE TITLE
Add background to text

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#21]
Currently it is very hard to read white text with black shadow on heterogeneous background. I suggest wrapping all text (at least those one related to stories/etc) with a semi-transparent frame that will make reading easier. Another option would be to change font to something not so eye-hurting. :)

**Comment by Andrettin** [comment]
On which backgrounds did you find text hard to read? The parchment backgrounds, or the smaller panels (used for the dialogues, etc.)?

**Comment by KroArtem** [comment]
For example, in the Encyclopedia -> Texts, when there are several paragraph, it's not pleasant to read.
However, texts on smaller panels used for dialogues is also hardly readable. The background there is ok but not the font/colour.

**Comment by Andrettin** [comment]
Yes, I agree about the encyclopedia ones.

The text on the smaller panels looks alright to me though (maybe because I've gotten used to them); when you mention the font, you mean that it should be darker or lighter?

**Comment by KroArtem** [comment]
The contrast is very high, I think so. That's why I have to stress my eyes to read the text. However, it'd be better to hear more opinions.

**Comment by KroArtem** [comment]
It was a nice year when I had a lot of spare time to spend on OSS and do some Wyrmsun gaming. Currently it's a bit harder to find time for this and today I read about possible switch to Godot.

I'm not a fan of huge amount of issues in a project that are very old and (probably) are not related to current codebase. I suggest closing all these tickets and will do for all my tickets here and in https://github.com/Andrettin/Wyrmgus
