### ISSUE TITLE
Save Map in map editor refers to Save Game

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#22]
If you want to save a map in map editor, it says Save Game. Not a big thing, though. :)

![2015-10-29 03-35-04](https://cloud.githubusercontent.com/assets/1813101/10822045/611daa92-7e66-11e5-8956-8f7322312ba9.png)

**Comment by Andrettin** [comment]
Fixed in https://github.com/Andrettin/Wyrmsun/commit/d6671489b04860c0202b5dd2643fc4d0fb81a7c8

Thanks for the report! It may not be a big thing, but it is improving the small things that gives the game polish :)
