### ISSUE TITLE
Caverns of Flame is too hard to complete

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#24]
Probably it's me who doesn't understand the goals, but I have enormous problems completing this quest. I tried to stand on those four velvet things that are near the centre of the map but it didn't help. I tried to go down as far as possible but it didn't help. Once I killed and destroyed the goblins' town on the left and came to those 4 things in the centre but it didn't help.

**Comment by Andrettin** [comment]
To win the mission, you need to step on the glyphs in the center of the map, and then survive until the time goes out. If you attack the goblins' base, it is possible that you may end up with too few troops to defend yourself against the Shinsplitter waves. Do you think the objectives are too unclear?

By the way, when testing the mission I noticed the miasma units now show a health bar... I fixed that here:
https://github.com/Andrettin/Wyrmgus/commit/8ebedc51c6d6d5f3c0f84cf794ffe2751801a7e4

**Comment by KroArtem** [comment]
I tried this once but didn't manage to survive. And actually I thought those "clouds" with health bars indicate that the volcano will erupt and was waiting when they'll "die"... :)
Will try the same strategy tomorrow and report.

**Comment by KroArtem** [comment]
Ok, managed to win but what bothers me sometimes is that I don't know how to stop units. Like "stay here and don't go anywhere".

I don't know how win conditions are triggered but if there is a need to stay on these glyphs for some time, it can be shown in up-left corner or somewhere else.

**Comment by Andrettin** [comment]
There is no need to stay in the glyphs for some time, you just need to activate one of them once.

To stop units and make them not go anywhere, press "T" or click on the "Stand Ground" button in the command panel. I think everything has been cleared up? So I'm closing this issue now, but if there's still something, let me know!

**Comment by KroArtem** [comment]
Yep, everything is ok, thanks for explanation. :)
