### ISSUE TITLE
Wyrmsun spends too much time if IP address field in multiplayer game is empty

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#25]
When IP address is empty, Wyrmsun tries to connect to.. I don't know what it tries to connect for so long. :)
Another things to do would be:
a) to show which IP-address you're trying to connect
b) to validate entered IP-address.

**Comment by Andrettin** [comment]
Good ideas, all done now :)

https://github.com/Andrettin/Wyrmsun/commit/85b9c0777c6fbf92032d8f7d5d68bec409e9b48d
https://github.com/Andrettin/Wyrmgus/commit/d933b0ee22e183ef9fde8cfda9375f632fa25706
