### ISSUE TITLE
Packaging issue, wrapper script

### ISSUE THREAD

**Issue by AMDmi3** [Andrettin/Wyrmsun#3]
I want to package wyrmsun for FreeBSD. It works fine by running wargus in data directory manually, however to install it systemwide it'll need a wrapper script and desirably .desktop file. The problem is that the game stores config and saved games in ```./wyr```. This is not acceptable for systemwide installation. Is it possible to make stratagus/wyrmgus use dotdir in user's $HOME? If not, it'll be nice to add canonical wrapper script into game repository which does mkdir and chdirs to e.g. $HOME/.config/Wyrmsun and then calls wyrmgus with path to game data.

**Comment by Andrettin** [comment]
It is possible to use the user directory instead of the game directory for save files and etc. To do this, set the ENABLE_USEGAMEDIR option to OFF.

**Comment by AMDmi3** [comment]
This works, thanks! Another question, is there anything in graphics/ I could use as an icon for .desktop file? Of course, adding official icon and desktop file to the repo would be even better.

**Comment by Andrettin** [comment]
Great :) About the icon, there's this one in the repo:
https://github.com/Andrettin/Wyrmgus/blob/master/src/win32/wyrmsun.ico

This is the original file:
https://dl.dropboxusercontent.com/u/1732902/Wyrmsun/w64.png

Another idea would be to cut a 32x32 square out of one of the icons for the units/buildings/etc. and make a .ico file out of that, if you want something different.
