### ISSUE TITLE
First-time player problem?

### ISSUE THREAD

**Issue by PhoenixRiver** [Andrettin/Wyrmsun#30]
I ran wyrmgus for the first time and got this message:

$ wyrmgus
Can't open file 'preferences.lua': No such file or directory
/usr/games/wyrmgus: line 5: 21946 Segmentation fault /usr/lib/games/wyrmgus/wyrmgus -d /usr/share/games/wyrmsun/ "$@"

I'm running Xubuntu 64-bit (14.04) and wyrmgus (1.5.2.-1~getdeb1 from Playdeb) reports:

$ wyrmgus -h
Wyrmsun v2.3.0, Copyright (c) 1998-2015 by The Stratagus Project
written by Lutz Sammer, Fabrice Rossi, Vladi Shabanski, Patrice Fortier,
Jon Gabrielson, Andreas Arens, Nehal Mistry, Jimmy Salmon, Pali Rohar,
cybermind and others.
[snip]

Seems like a file is missing but if you've run it before it's not a problem?

**Comment by Andrettin** [comment]
Closed as the issue has been solved and the parallel issue for Wyrmgus has been closed:
https://github.com/Andrettin/Wyrmgus/issues/41
