### ISSUE TITLE
Issues when loading up the Game.

### ISSUE THREAD

**Issue by Trensicourt** [Andrettin/Wyrmsun#31]
I downloaded Wrymsum the other day, because I was interested in it and that my computer cannot handle 3D games well. When I first I tried to load it, there was a .dll problem. It was easily fixed; however, the loading screen obstructed my path to gaming. It was obvious that a graphical error took place. This is what happened when I loaded the game after the .dll problem was fixed.

![issue-wrymsum](https://cloud.githubusercontent.com/assets/15918007/11260779/339c47be-8e3c-11e5-8b17-053141e70327.PNG)

The music was great though!

**Comment by Andrettin** [comment]
Hey, thanks for your interest in the game :)

Unfortunately, I'm not sure what could be causing this issue (no one has reported anything similar previously).

Maybe you're having an issue with OpenGL? You could try editing the /wyr/preferences.lua file, and change this line:
wyr.preferences.UseOpenGL = true

To this:
wyr.preferences.UseOpenGL = false

Let me know if this works!

**Comment by Trensicourt** [comment]
It works! Thanks you. I'll report more bugs as I play.

**Comment by Andrettin** [comment]
Great! :)
