### ISSUE TITLE
Check for possibility to create units should be done earlier

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#32]
Now this check is done when a player is 100% created and the only thing that is needed is to increment units number and release this unit from building. From my point of view this check should be done before the creation starts as it seems a bit odd when you cancel already created unit. Just my 2 cents so I don't insist on it. ;)

**Comment by Andrettin** [comment]
You mean that the unit training can be cancelled despite it having already appeared? If so, yes, this should absolutely be changed (I had never noticed it before). I'll take a look at the issue.

**Comment by KroArtem** [comment]
Proof:
![2015-11-21 02-12-32](https://cloud.githubusercontent.com/assets/1813101/11314305/6362c8aa-8ff5-11e5-928f-28a7b9f12835.png)

Moreover, if you cancel this unit when it's 100%, another one will start creating (even though it shouldn't)

**Comment by Andrettin** [comment]
I don't see anything wrong with that screenshot (other than the numbers floating above the units, which is a little odd)? And yes, if you cancel that unit another will begin producing, since there is another in the queue there.

**Comment by KroArtem** [comment]
Well, from my point of view (and it is based on old AoE, AoE II) if the limit is already reached, there is no need to create unit till 100% and only then say "insufficient supply"

**Comment by Andrettin** [comment]
Ah, I see what you mean now. Fixed:
https://github.com/Andrettin/Wyrmgus/commit/56fc86fda55a69975955438ca84c68145b605dfe
