### ISSUE TITLE
Not enough quests for Earth race

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#33]
A quest for one more technology point is required to be able to discover all techs for Human - Teuton.

**Comment by Andrettin** [comment]
The Teutons gain as many technology points as they need to get all of their techs. Which tech aren't you being able to acquire?

**Comment by KroArtem** [comment]
I'm playing quests so the question for me is whether it's possible to get no all points from one quest?

**Comment by Andrettin** [comment]
If you completed a quest and got no points, then it seems likely that it was a problem with the objectives not being set at the beginning; this way even if you defeated the opponent you would not get any points (as you wouldn't have completed a quest through its triggers). Maybe that happened to you? There were some such issues (which I fixed), but I'm not aware of any quests currently having that problem.

**Comment by KroArtem** [comment]
No, seems like it's ok, I just missed quest "Moving into Galicia" and didn't earn 3 points to discover catapult and its improvements. Closing this ticket, thanks. :)

**Comment by KroArtem** [comment]
Well, to be honest I didn't mention those quest as its icon is rather... pale and looks like it's already completed. Maybe there is a possibility to make it more colourful?
