### ISSUE TITLE
GSM setup has unobvious behaviour

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#35]
GSM setup could have some improvements. Consider I want to choose random world and 2666 year BC but it is not possible now. It's possible iif exact world is chosen.

**Comment by Andrettin** [comment]
Only 3000 BC is available in the random map (since it has no history). What do you propose for improving the GSM setup?

**Comment by KroArtem** [comment]
It's not clear I'm going to play random world as it says "Asa Tribe" which refers to the Earth world. Currently I don't have any suggestion.

**Comment by Andrettin** [comment]
Isn't it clear as the "World" drop-down is set to "Random"?

About the faction, in the random world map the factions from different world maps are mixed (with the Asa Tribe and the Modsogning Clan being selectable).

**Comment by KroArtem** [comment]
It became clear... now. :) But I still think this menu needs some reorganization. Let's leave this ticket open, maybe I (or you or somebody else) will have some ideas.

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
