### ISSUE TITLE
Lack of hero's name in dialogue window

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#36]
![2015-11-20 20-11-58](https://cloud.githubusercontent.com/assets/1813101/11311491/3dd8ce5e-8fe1-11e5-9605-1db13cce24fd.png)

Seems like this guy who is speaking should be Marbod but there is no name there. Moreover, when I was playing this quest I didn't have any guy with such name. Probably he has an empty name?

**Comment by Andrettin** [comment]
Thanks! Yes, there was a bug introduced in one of the latest changes which was causing him to have an empty name :P I've fixed it now :)
https://github.com/Andrettin/Wyrmgus/commit/39499800000c8f5ec718ca94b0edea85e468ff8b
