### ISSUE TITLE
[Feature Request] Implement check for savegame compatibility

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#38]
I've tried to load an old savegame and Wyrmsun silently exits with the following message:

```
/home/kroartem/SVN/Wyrmgus/src/unit/script_unittype.cpp:2153: CclDefineUnitStats: Unsupported tag: ForTheMotherland
Unsupported tag: ForTheMotherland
stack traceback:
    [C]: in function 'DefineUnitStats'
    [string ".//wyr/save/wut_.sav.gz"]:32: in main chunk
    [C]: in function 'StartSavedGame'
    [string "scripts/menus/load.lua"]:9: in function 'LoadGame'
    [string "scripts/guichan.lua"]:1344: in function 'RunProgramStartMenu'
    [string "scripts/guichan.lua"]:1398: in main chunk

```

So it may be a good idea to do checks whether it's possible to load game or not. However, I'm not sure when this check should be done: before showing existing savegames or before loading. In the first case, it could be rather slow if there are a lot of savegames. In the other case, just a message can be shown if savegame is not compatible.

**Comment by Andrettin** [comment]
Pretty much any version change will make old save games incompatible, so I would just assume that they wouldn't be compatible after a new release.

Checking whether save games are compatible would be nice, but it would require to somehow load the saved game without actually starting a game, and then processing that data to check for any incompatibilities; and this would have to be done for every save game; it sounds expensive performance-wise.

**Comment by KroArtem** [comment]
Well, an indicator with savegame version could be added so the only thing to be checked would be this integer.

**Comment by KroArtem** [comment]
I just want to raise this ticket again. As far as it seems now, save\load functionality just checks the directory for all files. Consider I create a file called test.sav in /wyr/save/ and try to load it in Wyrmsun. Unsurprisingly, it doesn't load. Moreover, I cannot delete this savegame ingame. I cannot use old savegames as they're incompatible. In my humble opinion, this piece of code should be redone. (yes, I understand it's not that interesting :))

As far as I can imagine, one more string should be added to .sav files that'll tell Wyrmsun's version. If it matches, then everything could be loaded. (of course, it won't be that easy, because some versions could be compatible). 

Another thing I noticed when I was trying to load empty .sav file was that all (?) images were loaded before it crashed. So I assume all images are loaded every time. Isn't it a good idea to find and use only those textures/pictures that are needed for current game?

**Comment by Andrettin** [comment]
It is a good idea, but it would require a restructuring of the saved game data, probably splitting it into two files like the map definitions, which have a map presentation file, with the info to be displayed in selection screens and etc., and a file containing the map data itself, loaded when the game starts.

Adding the possibility to delete saved games in-game is also a good idea.

About the images, the issue with loading only some of them is that it would be difficult for the game to know which ones will be used and which ones won't.

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
