### ISSUE TITLE
quest screen is empty

### ISSUE THREAD

**Issue by a-detiste** [Andrettin/Wyrmsun#39]
last update seems botched: "/home/wyrmgus/src/stratagus/script_quest.cpp:247: CclGetQuestData: Quest "On the Vanaquisl" has no player color.
error in error handling"

no way to get back either, had to `killall -9 wyrmsun64`

![empty](https://cloud.githubusercontent.com/assets/7994192/11480728/6e2442e0-9799-11e5-921d-b1bdb5846e70.png)

**Comment by Andrettin** [comment]
Thank you! Since I have the quests completed here, I didn't notice this issue. I have fixed it now for version 1.7.3:
https://github.com/Andrettin/Wyrmgus/commit/3e818c6c3e8b0c7ad0ac7ff63e819ebafc83bf52
