### ISSUE TITLE
Binaries in source code management

### ISSUE THREAD

**Issue by Mailaender** [Andrettin/Wyrmsun#4]
I thought about packaging this for openSUSE games. Found https://github.com/Andrettin/Wyrmsun/blob/master/wyrmsun.exe but in the source code repository and therefore also in the *source* tarball. Please upload binaries at https://github.com/Andrettin/Wyrmsun/releases instead.

**Comment by Andrettin** [comment]
On one hand, yes, I agree that it would be better to not have the binary on the repository itself. On the other, however, having the binary there makes it easier for people to try out the latest development version of the game between releases.

**Comment by Mailaender** [comment]
Which brings me to point number two on this: how do you compile the game. I can't find instructions or a build system. Having that in place will free you of the binary bloat in your SCM.

**Comment by Andrettin** [comment]
The source code for the binary is within a separate repository:
https://github.com/Andrettin/Wyrmgus

Is that what you were looking for?

**Comment by AMDmi3** [comment]
+1 to this PR. You could tag wyrmgus releases from time to time and attach binaries to them, this way wyrmsun users will be able to play the game without compiling anything, while keeping the repo clean from binaries.

**Comment by Mailaender** [comment]
See https://github.com/blog/1547-release-your-software

**Comment by Szunti** [comment]
And what about having wyrmgus as a submodule?, that would  connect an engine version with the wyrmsun data, which is needed anyway, because as I see most modification needs engine changes too.

**Comment by Andrettin** [comment]
That sounds interesting, how would I do that?

**Comment by AMDmi3** [comment]
Something along (in wyrmsun repo) ```git submodule add https://github.com/Andrettin/Wyrmgus.git wyrmgus && git commit```. Then, if you want to bring it up to date, fetch/checkout in wyrmgus/, then commit in wyrmsun. You could also add a top-level CMakeLists in wyrmsun which recurses into wyrmgus and probably also handles wyrmsun installation.

**Comment by Szunti** [comment]
http://www.git-scm.com/book/en/v2/Git-Tools-Submodules seems useful.

**Comment by akien-mga** [comment]
+1 for not keeping track of binaries in the main repo. Git is not really suited for hosting binaries, and that makes the git repository needlessly heavy (because when you clone the repository, you also have to clone the whole history of all updates to the .exe binary, and each update is a full 2 MB as you can't rely on diffs for binaries).

**Comment by akien-mga** [comment]
On the other hand I understand the will to provide a ready to test Windows binary, Windows players are rarely fluent in how to compile software. Maybe you could provide daily builds of the engine hosted somewhere else?

**Comment by Mailaender** [comment]
We use @AppVeyor at @OpenRA to automatically build and store nightlies. See https://ci.appveyor.com/project/OpenRA/openra/build/1.0.3804/artifacts for example.

**Comment by Andrettin** [comment]
Fixed in https://github.com/Andrettin/Wyrmsun/commit/31d52bd3faac9ebe742f4c15e626ccbb5c6187b9

**Comment by Szunti** [comment]
What about sdl.dll?
And you can also remove the binaries from history if you want git clone to be faster.
(https://help.github.com/articles/remove-sensitive-data/)

**Comment by Andrettin** [comment]
Ops! I had forgot about that, thanks for the heads up; I removed it now.

About the history, wouldn't doing that be problematic for past releases?

**Comment by Szunti** [comment]
I have no idea about releases.

**Comment by AMDmi3** [comment]
Well as the procedure changes all commits it **will** be problematic for everybody who verify tag or tarball contents or depend on specific commits (for example, FreeBSD port will break, as it verifies tarball checksum, which will change; I should update the port anyway though, so this is not really a problem), as well as for everybody who have local commits over your repository (seemingly there are none apart from a single outdated fork with some commits). On the other hand, it's 1/3 repository size decrease (414MiB→271MiB), and it should be done only once.
