### ISSUE TITLE
steam runtime in another location

### ISSUE THREAD

**Issue by a-detiste** [Andrettin/Wyrmsun#40]
On Debian & Ubuntu distros, the Steam runtime is located in ~/.steam

https://sources.debian.net/src/steam/1.0.0.50-6/debian/scripts/steam/

```diff
--- run.sh.orig 2015-11-30 19:30:29.930248849 +0100
+++ run.sh      2015-11-30 19:31:26.500734992 +0100
@@ -3,8 +3,11 @@
 # Run the game using the Steam runtime to get embedded libraries like libmikmod.so.2
 bits=$(getconf LONG_BIT)
 steamdir="${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime"
+steamdir2="${HOME}/.steam/ubuntu12_32/steam-runtime/"
 if [ -e ${steamdir}/run.sh ]; then
   exec ${steamdir}/run.sh ./wyrmsun${bits} "$@"
+elif [ -e ${steamdir2}/run.sh ]; then
+  exec ${steamdir2}/run.sh ./wyrmsun${bits} "$@"
 else
   echo "Can't find the Steam runtime in the expected path."
   echo "Please consult the linux_readme.txt file for more information."
```

**Comment by akien-mga** [comment]
Hm, interesting. Out of curiosity, do you know what was the rationale to differ from what upstream defines (at least on my distro I have only symlinks in ~/.steam, the real path is ~/.local/share/Steam, and we use the stock upstream setup: http://svnweb.mageia.org/packages/cauldron/steam/current/SPECS/steam.spec?view=markup)?

I'd think that Debian would be fine with using $XDG_DATA_HOME no?

The change would be harmless of course, and if some distros need it, it should be merged in :)

**Comment by akien-mga** [comment]
Well "merged in", now I understand why you did not make a PR directly, the file is not in the git repo, only in Steam :)

**Comment by Andrettin** [comment]
Thanks! I've added the new code to run.sh now and uploaded it together with version 1.7.3 to Steam.

**Comment by a-detiste** [comment]
Hi,

I digged in closed bugs & found this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737078

**Comment by akien-mga** [comment]
> I digged in closed bugs & found this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737078

Thanks! That's a lousy reason IMO, but well :) so be it.

**Comment by a-detiste** [comment]
Unrelated: I haven't ported `Game-Data-Packager` yet to Mageia, would you be interrested ?

It's about 7000 lines of Python + 156 .yaml game definitions with hashes for every single file;
with built-in support for Steam & lgogdownloader.

It's kin like a generic Wartool.

http://pkg-games.alioth.debian.org/game-data/

http://anonscm.debian.org/cgit/pkg-games/game-data-packager.git/tree/tools/game-data-packager.spec
