### ISSUE TITLE
Stuck in earth quest

### ISSUE THREAD

**Issue by a-detiste** [Andrettin/Wyrmsun#41]
Hi,

I've been playing along the quest.

I noticed two things:
- for me, on this screen, the "Previous Menu" button never works. Alt-F4 does work.

![wyrmsun](https://cloud.githubusercontent.com/assets/7994192/11779347/aeb0c06a-a25a-11e5-99d2-62c48ccc1c82.png)

- I did succeeded "The Bule Danube (Teuton)", but then when I got back at this screen, I'm not offered the next scenario nor a "You've succeeded the game" screen or something.

https://github.com/Andrettin/Wyrmsun/blob/ba766fe70650ee922477376f70e798e469e1a182/scripts/quests.lua

How do I get to play "Tror's Inheritance" & "Ottar's Lineage" listed in scripts/quests.lua ?

I don't my spoilers that much (as long as they don't reveal goldmines & enemy location),
maybe a webpage with the full campaign description would help me too.

I can provide some state files from `~/.steam/SteamApps/common/Wyrmsun/wyr`if that can help you
(or maybe those are "in the cloud" and you could snoop them ?)

**Comment by Andrettin** [comment]
Hey,

The Blue Danube quest is actually the last Earth one. I'm not sure about adding a "You've beaten all quests" message, since the idea is to add more quests eventually. I noticed that you haven't completed the "Moving into Galicia" quest yet, though (the last one on the first row); it is made available at the same time as "The Blue Danube" (maybe the town hall with black team color doesn't look distinct enough when compared to the grayed completed quests).

What happens when you click "Previous Menu" in the quests screen, it just does nothing? And thanks for the bug report!

What additional information do you feel would be good to have about the campaigns/quests?

Tror's Inheritance and Ottar's Lineage aren't playable (yet); I added them as hidden quests to quests.lua to test some experimental features.

**Comment by a-detiste** [comment]
> Moving into Galicia

ha well, hadn't seen it

> What additional information do you feel would be good to have about the campaigns/quests?

For WarCraft II I got this information in a paper magazine ;-) 

Maybe it's some job for a fan of the game, but shouldn't be shipped with the game to avoid spoilers.
http://wowwiki.wikia.com/wiki/Tides_of_Darkness_missions

-----

> What happens when you click "Previous Menu" in the quests screen, 
> it just does nothing? And thanks for the bug report!

Yes, just nothing & this looks like an actual bug & not a pebkac problem.

**Comment by a-detiste** [comment]
> I'm not sure about adding a "You've beaten all quests" message, since the idea is to add more quests eventually.

Some visual tip that the campaign is done would be good, both at the Quest selection screen & when the Quest is shown.
In "Plants Versus Zombies" you get an award on the corner of the screen.
Then this visual tip would revert automatically if new campaings are added.

-----

PS: this would be an awesome theme for a mod ;-)
https://en.wikipedia.org/wiki/The_Varangian_Way

**Comment by a-detiste** [comment]
> it just does nothing?

I mean, the widget does work (it is enable & can be depressed as excepted), but no event happens.

**Comment by Andrettin** [comment]
Adding a visual tip for when all quests are completed sounds good, I'll add that for the next version.

About the issue you were having with the quest screen, I've uploaded a new version now (1.8.0), which should fix the issue, but let me know if it persists.

A campaign about the Varangians would be really cool indeed :)

**Comment by a-detiste** [comment]
The menu issue is fixed

**Comment by Andrettin** [comment]
Great :)

I added a symbol indicating how many quests the player has completed for each world (it will be implemented in the game with the next patch):
http://andrettin.github.io/screenshots/screen_quest_badge.png

Besides the notification, the symbol itself changes according to how many quests have been completed.

**Comment by Andrettin** [comment]
After seeing the symbol in the quests screen a few times, it seems to stand out too much to me. So I've added a simple "X/X Quests Completed" text instead.

**Comment by a-detiste** [comment]
yeah, it'hard  getting the balance right
