### ISSUE TITLE
long swordman display incorrectly in map editor

### ISSUE THREAD

**Issue by a-detiste** [Andrettin/Wyrmsun#43]
I get most of the time a grey square instead.
I guess it's some .png alphe channel problem. Never seen this unit in-game (yet)

![long_swordman](https://cloud.githubusercontent.com/assets/7994192/11826166/d8400b6e-a383-11e5-9d92-d9a8aee381cf.png)

**Comment by Andrettin** [comment]
Thanks! Fixed in https://github.com/Andrettin/Wyrmsun/commit/7c90549aea2dde7c5f92d406e31e98c40ae7c5d1

This unit appears randomly in dungeons giving extra experience for rescuing it.
