### ISSUE TITLE
scandinavia map: IA wait patiently to be killed

### ISSUE THREAD

**Issue by a-detiste** [Andrettin/Wyrmsun#46]
the Varva farm is a nice touch

![wyrmsun](https://cloud.githubusercontent.com/assets/7994192/11920287/efe574a8-a76a-11e5-96f4-65a48461a355.png)

**Comment by Andrettin** [comment]
Thank you!

Fixed:
https://github.com/Andrettin/Wyrmsun/commit/fdad35a5d71b461c6afe998d31f0ed2a1f6f237c
