### ISSUE TITLE
How to build on linux ?

### ISSUE THREAD

**Issue by alketii** [Andrettin/Wyrmsun#5]
How to build on linux ?

**Comment by Andrettin** [comment]
Hello alketii, the repository of the engine's source code is here:
https://github.com/Andrettin/Wyrmgus

The compilation instructions are in the /doc/ folder.

If you have any issues with the compilation, let me know!

**Comment by akien-mga** [comment]
For the sake of completeness, while the engine is built (and e.g. make install'ed), you can run "stratagus" directly from the wyrmsun directory to start the game.

@Andrettin BTW it would be nice if you could rebrand wyrmgus completely, as in its current state it will be hard to package it and wyrmsun on Linux distributions which already provide upstream's stratagus.
