### ISSUE TITLE
Add possibility to "uncomplete" quests 

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#51]
Currently there is no way to start completing new quests from scratch, if I'm not mistaken.

**Comment by Andrettin** [comment]
That is true. But why do you want to do that? You can still replay quests after finishing them.

**Comment by KroArtem** [comment]
Why not? When I have all technology points I've got some temptation to use it and be more powerful than if I was completing it from scratch. This makes quests' completion not so challenging.

**Comment by Andrettin** [comment]
I see what you mean, but some players might accidentally reset their quests completed if that was available, which could be very frustrating.

**Comment by akien-mga** [comment]
A possibility would be to do as in similar strategy games with campaign scenarios: the progress is saved at the end of each quest and not overridden by newer quests, so your progress at the end of quest N will always determine how you start quest N+1 (even if you already completed all quests of the game). Then if you redo N and finish it, the saved state is overridden and it will also impact how you start next time you redo N+1.

**Comment by KroArtem** [comment]
Well, I still think such an option should be available (probably it shouldn't be that obvious and eye-catching).

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
