### ISSUE TITLE
"Level up" doesn't update heroes' interface

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#52]
I was playing the third quest where I had to subdue the natives and my hero leveled up. There is a slight remark that his menu didn't updated properly and I had to choose him again to be able to see an icon which leads to bonuses.
Secondly, I destroyed two buildings only by this hero and he didn't get any more XP.

Wyrmgus & Wyrmsun the latest.

**Comment by Andrettin** [comment]
Thanks! I'll look into fixing the interface update issue.

As for the second issue, buildings no longer grant XP since v1.8.0.

**Comment by KroArtem** [comment]
Ok, then I should rephrase this ticket. Let's speak about update issue. I assume an update method is forgotten there and after you choose an ability.
![2016-01-14 03-21-46](https://cloud.githubusercontent.com/assets/1813101/12312160/21661698-ba6e-11e5-8845-c44d1031ce2b.png)

I've chosen 1 ability on the previous lvl and one on this one, 2 are still not chosen but the menu interface is still in abilities window.

**Comment by Andrettin** [comment]
Thanks :)

It is fixed now:
https://github.com/Andrettin/Wyrmgus/commit/b2c84f0a49cd2279069c27d5bb5a754f35dfe740
