### ISSUE TITLE
Buras lose their mining if they do nothing for some time

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#53]
I had one bura locked between trees and a gold mine. He collected 100 gold and was staying there doing nothing (as he didn't have any opportunities to reach the centre). After some time he lost the gold. Is it intended?

**Comment by Andrettin** [comment]
That's a good question. It is intended as a way for them to keep cutting trees if they get stuck. Though I agree that it might look weird.

**Comment by KroArtem** [comment]
Is it documented somewhere? I didn't manage to find this information that's why created a ticket. Otherwise it's not a bad idea.

**Comment by Andrettin** [comment]
I believe it's documented somewhere for Stratagus, though off the top of my head I can't recall where.

Either way, I've added a tip about this to the loading screen tips:
https://github.com/Andrettin/Wyrmsun/commit/cfb35d16910d248665c5b6c4c3d8f26c2d8d5231

**Comment by KroArtem** [comment]
Ok, I consider it as "fixed" then. :)
