### ISSUE TITLE
Ambiguous tooltip

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#54]
![2016-01-14 03-18-09](https://cloud.githubusercontent.com/assets/1813101/12318730/9bf08f80-baad-11e5-9a41-75087321f254.png)

I've destroyed a building there and all the time till the end of a mission I had this tooltip in this place saying about destroyed 3x3 place.

**Comment by a-detiste** [comment]
I had the same with chopped wood in the mine tunnel with the wyvern

**Comment by Andrettin** [comment]
Yeah =/ I've seen this as well. I'm not sure what's causing it, I'll have to investigate further.

**Comment by Andrettin** [comment]
I've submitted a fix which should solve this issue:
https://github.com/Andrettin/Wyrmgus/commit/50d8acfde6ee46d6bf7d5a0c032b6a6ca4728ae2

**Comment by KroArtem** [comment]
I haven't seen this tooltip for a while so closing this ticket.
