### ISSUE TITLE
Incorrect diplomacy window

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#57]
I was playing a quest where my aim was to collect 8000 gold. I checked diplomacy and this is what I saw:

![2016-01-16 02-37-53](https://cloud.githubusercontent.com/assets/1813101/12401691/2b9079e6-be39-11e5-9774-3067d50f289d.png)

Btw, I\m the only active tribe on the map in this quest.

**Comment by Andrettin** [comment]
Thank you, it's fixed now :)

https://github.com/Andrettin/Wyrmsun/commit/449f2583699634bd820fda31cade2709b08e6054
