### ISSUE TITLE
Potion of decay doesn't work correctly

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#59]
See the screenshot. I took this potion twice but didn't get any damage.

![2016-01-19 09-24-44](https://cloud.githubusercontent.com/assets/1813101/12411322/bd44de72-be8e-11e5-97e1-913c7bb04af9.png)

**Comment by Andrettin** [comment]
Thank you, fixed now :)

https://github.com/Andrettin/Wyrmgus/commit/f4cf36088f1a3fd574db52b82db028579214e436
