### ISSUE TITLE
Units 

### ISSUE THREAD

**Issue by paipan** [Andrettin/Wyrmsun#6]
When units are moving (not attack-move) they react on enemies (especially if attacked) and drop their current order (Move). It is not very convenient, for example in survival missions: you decide that "has to survive" unit should exit from combat already, but he rushes in again and dies.
*sorry, forgot to update issue name

**Comment by Andrettin** [comment]
Yes, I agree, and actually, previously units didn't counterattack if having been ordered to move and etc., but I changed that based on player feedback that it was confusing that they wouldn't counterattack. However, I was never entirely happy with the change for exactly the reasons you mentioned, and had been considering reverting it. I've reverted the change now.

**Comment by paipan** [comment]
I have actually seen this(maybe) video, when presenter said that "units don't react well" a few times, but according to video, units react perfectly normal.
Anyway, works perfectly fine now, thanks.
