### ISSUE TITLE
Miners can level up

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#60]
Though it doesn't give them any advantages (or I misunderstood something)

**Comment by Andrettin** [comment]
They get +15 health after leveling up (the same happens to other units when leveling up if the learnable abilities have been exhausted).

**Comment by KroArtem** [comment]
It seems like it is not stated anywhere, so why not putting it in help.lua? :)

**Comment by KroArtem** [comment]
Ok, seems like now it's there, closing ticket.
