### ISSUE TITLE
If miner has 100 lumber he doesn't understand "collect lumber" aim

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#62]
I had a miner and he collected 100 lumber, I said him to collect lumber (as it is much easier then to forward him to the main building and then say him to collect lumber again) but he didn't react at all. I think it's not hard to add such a small but useful improvement.

**Comment by Andrettin** [comment]
Very good idea. I've implemented it now:
https://github.com/Andrettin/Wyrmgus/commit/08a4ce39fc9ff9434beb4ebac78ef928348fe8be
