### ISSUE TITLE
Overlapping text in menu

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#64]
See screenshot, Smithy's name is overlapping.
![screenshot from 2016-01-27 22 28 21](https://cloud.githubusercontent.com/assets/1813101/12631959/9e3e8194-c565-11e5-909c-7826426f039d.png)

**Comment by Andrettin** [comment]
Thank you! I've fixed it now:
https://github.com/Andrettin/Wyrmgus/commit/e712261562e82ce31e912e14cdccef435239ca50
