### ISSUE TITLE
Strange delimiter in special items descriptions

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#66]
There are some | and / delimiters, is that normal?

![screenshot from 2016-02-02 02 23 17](https://cloud.githubusercontent.com/assets/1813101/12767650/809b66ec-ca1b-11e5-8a87-2ee4102fdd2f.png)

**Comment by Andrettin** [comment]
Yes, that is normal. They are notations for poetry. The "|" denotes a caesura, while the "/" separates one verse from another.

**Comment by KroArtem** [comment]
Ok, I was just confused with this. Closing ticket then.
