### ISSUE TITLE
Disable shortcuts when buttons are disabled

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#67]
In GSM, when you start a battle, it's not possible to save and load, buttons are greyed and inactive. However, it's possible to save game with F11 and try to load it with F12. Then Wyrmsun doesn't seem to behave properly.

**Comment by Andrettin** [comment]
Thank you! This is fixed now:
https://github.com/Andrettin/Wyrmsun/commit/da830f10c778f0dd47b9eae617d19e701b9f9689
