### ISSUE TITLE
Destroying your own hall leads to some weirdness

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#68]
When you start a game, order your units to attack your hall. After it's destroyed, you'll have a notification. Wait 30 seconds and you'll see some magic :) Have a look at minimap.

![screenshot from 2016-02-03 03 02 48](https://cloud.githubusercontent.com/assets/1813101/12768776/314bc02a-ca23-11e5-8197-de4e8dc389cd.png)

Damn, seems like I miss those days when I was working as a QA intern.
And yes, on this screenshot my units attack golden deposit. :)

**Comment by Andrettin** [comment]
Thank you! I've pinpointed the cause of the issue and fixed it:
https://github.com/Andrettin/Wyrmgus/commit/715749b1327cc145a75981839ac7863e4fad8ea4
