### ISSUE TITLE
Ambiguous explanation for rings

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#69]
Currently it seems like it's possible to wear two rings at a time. (rather reasonable, one on the left, one on the right hand). However, when you equip two rings one of their descriptions becomes ambiguous.

Consider this:
1) Ring of regeneration. +1 regeneration
2) Vicious ring. +2 damage.
Now equip 1) and then 2). For 2) there will be no description, for 1) there will be Regeneration +1, damage -2
Now de-equip all. Equip 2) and then 1). For 1) there will be no description, for 2) there will be regeneration -1, damage +2.

Attaching screenshots.
![screenshot from 2016-02-03 03 30 04](https://cloud.githubusercontent.com/assets/1813101/12769163/7fa431dc-ca26-11e5-9049-7852df63eb00.png)
![screenshot from 2016-02-03 03 30 31](https://cloud.githubusercontent.com/assets/1813101/12769162/7fa340c4-ca26-11e5-8ad6-7685533f498c.png)

**Comment by Andrettin** [comment]
Good catch. I've fixed this now:
https://github.com/Andrettin/Wyrmgus/commit/aad67397aa87de17b8387346cc1c4295fe3fcf04
