### ISSUE TITLE
Usual units cannot use food and potions

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#70]
Currently there is a regression (or a feature) because my kriegers were not able to eat food or potions

![screenshot from 2016-02-05 00 02 26](https://cloud.githubusercontent.com/assets/1813101/12832160/62c859e2-cba9-11e5-8ca0-653a9c076f35.png)

**Comment by Andrettin** [comment]
Thank you, I've fixed it now :)

https://github.com/Andrettin/Wyrmgus/commit/51b70cd8444690e4db894551674862c3a883331c
