### ISSUE TITLE
Slime can sit into towers

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#72]
No comments... :)
It was indeed a slime!
![2016-02-24 04-05-01](https://cloud.githubusercontent.com/assets/1813101/13277343/52e68e06-dad9-11e5-9dab-90b17f79e5a1.png)

**Comment by Andrettin** [comment]
Strange :) I'll see if I can reproduce it.

**Comment by Andrettin** [comment]
Sorry for not giving an update on this earlier; unfortunately I haven't been able to reproduce this so far.

**Comment by Andrettin** [comment]
Fixed issue with the latest commits to Wyrmgus and Wyrmsun, and with the help of the bug description here:
http://steamcommunity.com/app/370070/discussions/1/2906376154329289288/
