### ISSUE TITLE
Incorrect message in results screen

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#73]
We were allies with one of the tribe but they're counted as enemy. I think it was lggi tribe.
![2016-02-24 04-31-31](https://cloud.githubusercontent.com/assets/1813101/13277403/abd54778-dad9-11e5-9005-454da0e84237.png)

**Comment by Andrettin** [comment]
Unfortunately, I couldn't find any flaw in the relevant code, in /scripts/menu/results.lua:

```
			if (ThisPlayer.Index == i) then
				name = name .. " - You"
			elseif (ThisPlayer:IsAllied(Players[i])) then
				name = name .. " - Ally"
			elseif (ThisPlayer:IsEnemy(Players[i])) then
				name = name .. " - Enemy"
			else
				name = name .. " - Neutral"
			end
```

Maybe you attacked your ally by mistake and they became hostile to you as a consequence? If you order an attack against an ally or neutral AI they will change their diplomatic stance with you to hostile.

**Comment by KroArtem** [comment]
yep, my workes attacked his mine as they were not able to get into it and collect gold/silver/copper, they were just staying in front of mine. I had to destroy it and build my own mine. Btw, it was the last building of my ally, all the others were destroyed by our enemy.

**Comment by KroArtem** [comment]
Ok, the question is why did I have to destroy my ally's mine?

**Comment by Andrettin** [comment]
I was thinking the same when I read what you posted. I made it so now you can harvest from an ally's mine:

https://github.com/Andrettin/Wyrmgus/commit/81ca3616fefebaadcabbb7ca1296604bc70fd008

I think the AI leaving minor buildings like farms and mines standing is alright, since they aren't required for victory.
