### ISSUE TITLE
Minimap is not updated when mine disappears

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#75]
As you can see, there is no mine on the place where minimap says it is.

![2016-02-25 02-41-07](https://cloud.githubusercontent.com/assets/1813101/13305358/d7ba85c8-db6b-11e5-8aba-80e4e3a7fd02.png)

**Comment by Andrettin** [comment]
I'll look into it. I also see from the screenshot that some of the trees have regrown incorrectly (lacking their top part).

**Comment by KroArtem** [comment]
Yup, the problem with trees appeared in different occasions after trees update, so I thought you already know about it. :) Apart from this problem, I remember some problems with different tilesets.

**Comment by Andrettin** [comment]
Which problems did you see? The tile transitions in forest tilesets look weird now, but that's just temporary until the pine tree and rock tiles get reworked. Did you see anything else?

**Comment by KroArtem** [comment]
I think these were mostly tile transitions, if there is something else, I'll report with appropriate screenshots.

**Comment by Andrettin** [comment]
I managed to reproduce this issue, find its cause and fix it now:
https://github.com/Andrettin/Wyrmgus/commit/ee6a843f79f4309fe5c0485d7dad145b4f8ab575
