### ISSUE TITLE
Steam linux version lacks liboaml_shared.so

### ISSUE THREAD

**Issue by akien-mga** [Andrettin/Wyrmsun#79]
The Linux version on Steam does not start since the 2.0.0 update because the liboaml_shared.so library is missing: 
```
/media/data/Jeux/SteamApps/common/Wyrmsun/wyrmsun64: error while loading shared libraries: liboaml_shared.so: cannot open shared object file: No such file or directory
```
You'd need to either bundle the library, or link against it statically when building.

**Comment by akien-mga** [comment]
Maybe adding a ``FORCE_STATIC_OAML`` option and use it here would do the trick: https://github.com/Andrettin/Wyrmgus/blob/master/CMakeLists.txt#L878

**Comment by Andrettin** [comment]
Thanks for the PR Akien, so this is fixed now :)
