### ISSUE TITLE
Multiple building  selection enhancement

### ISSUE THREAD

**Issue by Szunti** [Andrettin/Wyrmsun#8]
The only other game I know where it is possible is starcraft II. And it is useful, because you can easily train units from all of them.

So what is still missing:

- [ ] Selecting other buildings with shift. (Why not?)
- [ ] When multiple buildings are selected and you click on train give the command to the building that will be able to do it first. So when you train 4 unit instead of 

    BARRACK1 | BARRACK2 | BARRACK3
----------------|----------------|----------------
unit1|
unit2|
unit3|
unit4|

    You should get:

    BARRACK1 | BARRACK2 | BARRACK3
----------------|-----------------|-----------------
unit1            |     unit2         |           unit3
unit4            |

**Comment by Andrettin** [comment]
Not being able to select other buildings via shift-click was an overlook. That's fixed now, and I also implemented your suggestion for training orders given to multi-selected buildings. Thanks!

**Comment by Szunti** [comment]
Only missing part is displaying what they are doing in the bottom panel.

And maybe lifting the restriction on the same type of buildings.

**Comment by Andrettin** [comment]
True, but since it is a multi-selection there isn't much space left to show what each one is doing.

As for lifting the restriction of the same building type, I'm not sure that would be very useful (since they have different commands available to them), except in the case of the town hall/stronghold pairings.

**Comment by Szunti** [comment]
Starcraft II show the actions of each afaik. And if the units have different shortcuts, like the b for Bura and e for Elara, then selecting both the warlodge and the town hall lets you easily train either of them.

Of course it means actions need different shortcuts. And there should be enough space for them in the bottom panel. Although I think it spoils the player a bit too much.

About the multi-selection space issue, maybe a small icon of trained unit above the buildings icon?
