### ISSUE TITLE
Custom game menu didn't switch to hints menu

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#80]
As it is said in title, when I started custom game, it started loading with this:
![2016-03-21 13-08-37](https://cloud.githubusercontent.com/assets/1813101/13937137/0f945b2a-efdc-11e5-934f-6be53d242632.png)

**Comment by Andrettin** [comment]
Thanks for the bug report :) I've encountered this as well (but only when using SDL rendering). Unfortunately I still have to find the root of the issue, though.

**Comment by KroArtem** [comment]
Probably these things are related:
![2016-03-29 03-00-41](https://cloud.githubusercontent.com/assets/1813101/14093968/176430b4-f563-11e5-9fcb-313ab8b4f327.png)

**Comment by Andrettin** [comment]
Hmm... quite strange. Are you using OpenGL rendering or not?

**Comment by Andrettin** [comment]
About the issue with the results screen - it is a separate problem than the one with the loading background not appearing; I've fixed the results screen issue with the latest couple of commits to Wyrmsun and Wyrmgus.

**Comment by Andrettin** [comment]
Fixed now :)

https://github.com/Andrettin/Wyrmgus/commit/cc23ecdc37a6a50dc5faa0449efe7a470c45d529
