### ISSUE TITLE
Stumps are shown on unexplored area

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#81]
Have a look at this pic, the bottom of the minimap has dots which indicate places where stumps are situated. They probably appeared there when enemy's flying creature explored those places and he was also revealed so I was able to see what he sees.

![2016-03-21 13-19-46](https://cloud.githubusercontent.com/assets/1813101/13937216/b1e4f84e-efdc-11e5-892b-3810ddee91b4.png)

**Comment by Andrettin** [comment]
Thank you! This should be fixed now:

https://github.com/Andrettin/Wyrmgus/commit/68182a9c8db1f6813ffb82b68eacf51023bddb98
