### ISSUE TITLE
DLC is still required

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#82]
When I was trying to launch custom game (random world, random valley, with my custom hero) I had the following error:
```
Can't open file: No such file or directory
Can't load the graphic 'dlcs/brising_faction_flair/graphics/units/brising_round_shield.png'
```

**Comment by Andrettin** [comment]
Ops sorry, I've fixed it now:

https://github.com/Andrettin/Wyrmsun/commit/ea1005796d0c1a03b778c1baaddc1ecd63c46373
