### ISSUE TITLE
liboaml_shared.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chenshuiluke** [Andrettin/Wyrmsun#84]
Good night guys. I just installed wyrmsun through steam, but it won't even open. This is the output from the commandline: 

    ERROR: ld.so: object '/home/luke/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from
    LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
    ERROR: ld.so: object '/home/luke/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from
    LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
    /home/luke/.local/share/Steam/steamapps/common/Wyrmsun/wyrmsun32: error while loading 
    shared libraries: liboaml_shared.so: cannot open shared object file: No such file or directory
    Generating new string page texture 120: 128x256, total string texture memory is 917.50 KB
Any help will be much appreciated

**Comment by akien-mga** [comment]
Thanks for the report, this is indeed a bug due to my recent change to the buildsystem, I'll make a pull request so that @Andrettin can create fixed binaries.

**Comment by Andrettin** [comment]
Fixed now thanks to Akien, and the new binaries have been uploaded to Steam :)
