### ISSUE TITLE
Units should be removed from map when story dictates

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmsun#86]
In the Hills of the Shorbear Clan quest, you have to move Rugnur to one spot and the envoy to another, and when you move one of them into place, he just sits and waits until the other is in place, which not only looks weird but also opens up the possibility for one of the Shinsplitter warriors to kill the waiting unit (when he's allegedly fled for parts unknown).  If there is a way to remove a unit from the map without killing him, this would be a good time to do that.

**Comment by Andrettin** [comment]
That's a good point; I've fixed that now:
https://github.com/Andrettin/Wyrmsun/commit/e1687726c7767cd373e9888dae0b02706012f867
