### ISSUE TITLE
Mud to logged area transition

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmsun#87]
Not sure if this is an engine bug or artwork related, but toward the center of the screen you see a jumbled area where the cleared/logged area meets the dark patch (mud?) and it looks wrong somehow... maybe a missing transition tile?

![screenshot from 2016-03-30 17 06 20](https://cloud.githubusercontent.com/assets/692397/14158431/0c3a1f32-f69e-11e5-9b56-121e94581e01.jpg)

**Comment by Andrettin** [comment]
Thanks for the bug report! It was a small mistake with the map file, which I've now fixed:
https://github.com/Andrettin/Wyrmsun/commit/a6ac6b7c26c51bda43f0259257fad2b23a5fe251
