### ISSUE TITLE
Can't Run Wyrmsun in Debian 8

### ISSUE THREAD

**Issue by srukle** [Andrettin/Wyrmsun#88]
I built Stratagus from source. I'm currently running the Ubuntu 14.04 engine from the PPA.
https://launchpad.net/~stratagus/+archive/ubuntu/ppa

When I go into the folder I stored Wyrmsun and start Stratagus, I get this output:

`stratagus-2.4.0/src/stratagus/script.cpp:1975: CclFilteredListDirectory: Forbidden directory
Forbidden directory
stack traceback:
	[C]: in function 'ListDirsInDirectory'
	[string "scripts/stratagus.lua"]:52: in main chunk
`

**Comment by johndh** [comment]
Do you mean the regular Stratagus engine (https://github.com/Stratagus/Stratagus) or the Wyrmgus fork (https://github.com/Andrettin/Wyrmgus)?

**Comment by srukle** [comment]
I'm using the "regular" Stratagus engine. Does it not work with Wyrmsun. The docs imply it should, but Wyrmsun never claims this.

**Comment by KroArtem** [comment]
For Wyrmsun you should use Stratagus's modified engine known as Wyrmgus. Some changes were applied to upstream (stratagus) but engines are not compatible.

**Comment by srukle** [comment]
I was able to successfully to play the game with the forked engine.

https://github.com/Andrettin/Wyrmgus/issues/93

**Comment by Andrettin** [comment]
Great that everything is working now :) Yes, building instructions would be really good.
