### ISSUE TITLE
[Feature request] Display Temple range

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#89]
It'd be cool to see in what radius temples' healing works.

**Comment by Andrettin** [comment]
I agree, though I also worry that it could be add a bit too much clutter if the aura range showed up at all times. One option would be to make it appear only when hold-clicking the unit (like is already done for the sight range).

**Comment by KroArtem** [comment]
yes, I was thinking about the same thing, showing range only when Temple is chosen.  However a highlighted glowing area with a lot of special effects indicating healing area would be also nice. :)

**Comment by Andrettin** [comment]
Done :)

https://github.com/Andrettin/Wyrmgus/commit/e15a3085bc07e759a96aa07f022a38cd13071692

Having the circle with more special effects would be pretty cool, but that would likely require new graphics.

**Comment by KroArtem** [comment]
Yup, I understand, just imagine effects from some AAA games  :) (don't know any modern games though)
