### ISSUE TITLE
Hard to see which units are mine

### ISSUE THREAD

**Issue by Szunti** [Andrettin/Wyrmsun#9]
When my germanic units fight with other germanic units, I can't tell which ones are mine, we are winning or losing, to retreat or not.

Drawing a circle with teamcolor under units for example would help a lot.

**Comment by Andrettin** [comment]
You mean a circle only when they are selected? Or have it always appear?

**Comment by Szunti** [comment]
Always and on every unit, so in a 2v2 I can also see which units are allies. 

There is the green rectangle when they are selected, but I think it's important to see the status of the battlefield without clicking.

**Comment by Andrettin** [comment]
Yes, I see. I think it would be a good thing to have as an option, I'll look into the code necessary for that.

**Comment by Andrettin** [comment]
Option to display a player-colored rectangle below units added in https://github.com/Andrettin/Wyrmsun/commit/6814b64a856fbc8ee05553f22df306fd668cb6d5 and https://github.com/Andrettin/Wyrmgus/commit/3cb1be3c09e9377dda1588fba4c60659e199a6a0

**Comment by Szunti** [comment]
After trying it out, I got this on The Home of the Boii mission. Units are mostly mine, buildings are not.
It seems we have really similar colors. Maybe that's the real problem. Also the corpses could be without it imo.

![wyrmsun-rect](https://cloud.githubusercontent.com/assets/1443881/7901932/a65a6cf8-07a1-11e5-8e79-603e8191e681.jpg)

Otherwise I think these rectangles are a bit obtrusive. I thought something like this:
(yellow ellipse under bottom right unit)

![wyrmsun-circ](https://cloud.githubusercontent.com/assets/1443881/7901956/6a1a12c4-07a2-11e5-83a2-ca294009ccec.jpg)

**Comment by Andrettin** [comment]
I changed the player-colored rectangles into filled semi-transparent circles now. I agree that corpses shouldn't have it, I implemented that now as well.

About the colors, yes, it seems like some tones of the orange are too similar to some of the brown tones...

**Comment by Szunti** [comment]
Thanks.
