### ISSUE TITLE
Overlapping icons in transport unit

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#90]
![2016-04-11 03-05-35](https://cloud.githubusercontent.com/assets/1813101/14413978/f15775ce-ff9a-11e5-8549-7bc1f4ec0680.png)

My archers are overlapped in transport unit window.

**Comment by Andrettin** [comment]
Thanks!

I've fixed it now (the transport ships weren't supposed to have stand ground buttons, that was an oversight):
https://github.com/Andrettin/Wyrmgus/commit/411e6384853cc44f3d17dd331f55df9c16ceaec0

Also, I see an issue with a tree tile in the top-right; has that occurred before to you?

**Comment by KroArtem** [comment]
I don't remember this problem with tree tile before. There was another problem with trees but afair it was fixed.
