### ISSUE TITLE
Bura standing on tree tiles

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#91]
![2016-04-14 02-28-04](https://cloud.githubusercontent.com/assets/1813101/14512865/e46e3252-01f3-11e6-87d2-215cb16c1084.png)

P.S. Yes, I have one hero for cheating. :)

**Comment by Andrettin** [comment]
Thanks! It was a problem with the graphics for cleared terrain not being updated under shared vision properly; I've fixed it now:
https://github.com/Andrettin/Wyrmgus/commit/6e976b84e693ceb851123e676d2dc57b61b778e4
