### ISSUE TITLE
Trees appear immedeately after a buidling is destroyed

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#93]
![2016-04-22 04-28-53](https://cloud.githubusercontent.com/assets/1813101/14741376/d8574530-08a6-11e6-8f77-96bf8922fd05.png)

My catapult just destroyed town hall and a square of tree appeared immediately on the place it stood. There is also a shell-hole on those place, see screenshot.

**Comment by Andrettin** [comment]
Thank you! I've made it so now the "regeneration counter" remains at 0 when the tile is occupied by a building (previously the counter advanced, but the regeneration itself was stopped if the tile was occupied), to avoid this sort of situation:
https://github.com/Andrettin/Wyrmgus/commit/e27145f94614cb6e6be40229488231f2027b46fe
