### ISSUE TITLE
the Mighty Rat

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#94]
That's truly a mighty rat :) Not sure rats should have these prefixes.

![2016-05-16 17-28-38](https://cloud.githubusercontent.com/assets/1813101/15292927/94501f94-1b96-11e6-9920-8ff8e31cc1b3.png)

**Comment by Andrettin** [comment]
Oups! Thanks for letting me know :)

I think it's fine for animals to have this sort of nickname (they only get ones related to physical traits so they don't get weird ones), but of course this shouldn't happen if they have no proper name. I've fixed it now:
https://github.com/Andrettin/Wyrmgus/commit/eca6915a14e48259ba9acabbf9bba9aaeb5a846a
