### ISSUE TITLE
Archers sitting in towers are not healable

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#95]
If my tower is in temple's range, archers, sitting in this tower, are not healed. Not sure whether it's correct behaviour or not.

**Comment by Andrettin** [comment]
I hadn't considered it, but they probably should benefit from the aura. I'll look into the issue.

**Comment by Andrettin** [comment]
Fixed now :)
https://github.com/Andrettin/Wyrmgus/commit/c86ecf11181ee356f776b78255ee75745ff1aebf
