### ISSUE TITLE
Quests don't switch to Tech Tree menu

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#97]
I'm not sure whether it's bug or a new feature, but when you win a quest (playing for the first time), you don't switch to Tech Tree menu.

**Comment by Andrettin** [comment]
It was a bug, thanking for reporting it! I've fixed the issue:
https://github.com/Andrettin/Wyrmsun/commit/663dcb146b517e6a608f8474acc38cad783212e5

**Comment by KroArtem** [comment]
If you load saved game, it still doesn't switch you to Tech Tree.

**Comment by Andrettin** [comment]
Thanks :) It's fixed now:
https://github.com/Andrettin/Wyrmsun/commit/4085a172dd37101be0be3c9bfe4d76b1d5f0454b

**Comment by KroArtem** [comment]
Another small thing: when you got a message "achievement unlocked, blah-blah-blah", it returns to the main menu, not to the quests' window or tech tree window.

**Comment by Andrettin** [comment]
Weird; it is working fine for me. Which quest/achievement was it, and was it a saved game?

**Comment by KroArtem** [comment]
The quest was "The Razing of Opitergium"

**Comment by Andrettin** [comment]
I've tried loading a saved game from that quest and completing it to gain the achievement, but no problem happens. The achievement is gained with a black screen behind the "Achievement Unlocked!" dialog (as it should), and after clicking the button in the dialog, I am properly taken to the Results screen. Maybe one of the latest commits fixed the issue?

**Comment by KroArtem** [comment]
Will recheck, but not so fast.
