### ISSUE TITLE
Self-built farms

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#98]
I've started to build farm and then switched to build Carpenter Shop. Suddenly I saw that Farm builds itself without any workers! See screenshots.
![2016-07-05 10-58-46](https://cloud.githubusercontent.com/assets/1813101/16578255/97627d22-42aa-11e6-8d6a-e44cbf21f937.png)
![2016-07-05 10-59-53](https://cloud.githubusercontent.com/assets/1813101/16578256/97639522-42aa-11e6-8fc1-54607fdce884.png)
![2016-07-05 11-15-05](https://cloud.githubusercontent.com/assets/1813101/16578257/9764a7d2-42aa-11e6-901a-237466038814.png)

**Comment by Andrettin** [comment]
Thank you! I hadn't noticed that before. Buildings without workers were self-constructing (albeit very slowly). This is fixed now:
https://github.com/Andrettin/Wyrmgus/commit/8eb3f3b911d62c40a64155176ffcd74af8680f6f

**Comment by KroArtem** [comment]
Seems like building do the same thing but when they're attacked.

**Comment by Andrettin** [comment]
You mean they lose HP over time when burning? If so, that's intentional.

**Comment by KroArtem** [comment]
Hm, yes,somehow I missed this feature.
